spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .html

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/shoppingdata?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/xhy/shoppingsystem/mapper/*.xml
  type-aliases-package: com.xhy.shoppingsystem.pojo
